### ISSUE TITLE
Remove emails from delegation dropdown

### ISSUE THREAD

**Issue by davefrey** [liquidvotingio/decidim-module-liquidvoting#100]
Currently our dropdown of delegates presents delegate names, with a value of their email -- which is a privacy issue:
```html
<option value="participatory_process_2_admin@example.org">Agripina Spencer</option>
```
Instead we should use a different value (the user id? or a disposable id?) and translate that into the email for the LV api call.

**Comment by oliverbarnes** [comment]
yeah, I think the user id (within decidim), to be exchanged by the email on the controller, before submitting the delegation?

**Comment by davefrey** [comment]
Agreed. I think GDPR considers database keys to warrant some privacy consideration but it really doesn't feel relevant here.

**Comment by oliverbarnes** [comment]
Good point, we had some previous discussion on this on the api repo, with some references about how GDPR views uuids:

https://github.com/liquidvotingio/api/issues/218#issuecomment-802808680

I just searched again, and am getting hits saying if the id is next to another piece of personal data, so that the id can be used later to identify a person, is a GPDR violation. 

I think this is work looking into, actually, to figure out a clear strategy on our end. In our case, if the decidim instance is integrating with our hosted API, we're also a third-party, which compounds to the problem.

Maybe the ids can be encrypted? This quick search didn't give me any clear strategies. We should look at how Decidim handles ids, and look into whether Rails addresses this in any way.
