### ISSUE TITLE
Bump the module and the demo to Decidim 0.23

### ISSUE THREAD

**Issue by davefrey** [liquidvotingio/decidim-module-liquidvoting#33]
Our demo development is currently based on Decidim 0.22.0. Bumping to 0.23 will not only get us more current, but will move us base the React component that is removed in 0.23 (the POST /api logfile noise is kind of a pita in dev).

Note two repos affected:
* liquidvotingio/decidim-module-liquidvoting (including the `version.rb` file)
* liquidvotingio/liquid-decidim-demo

**Comment by davefrey** [comment]
Our friends at coopdevs did this same work recently: https://github.com/coopdevs/decidim-module-action_delegator/pull/80

**Comment by oliverbarnes** [comment]
Changes to decidim-proposals since 0.22, gleaned from the changelogs:

## 0.24.0.rc2 changelog
[decidim/CHANGELOG.md at release/0.24-stable · decidim/decidim · GitHub](https://github.com/decidim/decidim/blob/release/0.24-stable/CHANGELOG.md)


* Fix non-unique IDs element in filter hash cash  [#7533](https://github.com/decidim/decidim/pull/7533) 
* Fix cells caching by using cache_key_with_version instead of cache version  [#7556](https://github.com/decidim/decidim/pull/7556) 
* Fix user profile timeline activity cards texts showing "New resource" on updates  [#7558](https://github.com/decidim/decidim/pull/7558) 
* Improve moderation panel  [#6677](https://github.com/decidim/decidim/pull/6677) 
* Add locales for cost report  [#6767](https://github.com/decidim/decidim/pull/6767) 
* Allow user to drag address on proposal map  [#6291](https://github.com/decidim/decidim/pull/6291) 
* Simplify collaborative drafts wizard  [#7239](https://github.com/decidim/decidim/pull/7239) 
* Proposal preview with full text and attachments  [#7248](https://github.com/decidim/decidim/pull/7248) 
* Import proposals from a spreadsheet  [#7084](https://github.com/decidim/decidim/pull/7084) 
* Allow multiple lines in announcement block  [#7341](https://github.com/decidim/decidim/pull/7341) 
* Let admins delete proposal attachments  [#7259](https://github.com/decidim/decidim/pull/7259) 
* Feature proposal infinite edit time  [#7406](https://github.com/decidim/decidim/pull/7406) 
* Fix i18n capitalizations  [#6784](https://github.com/decidim/decidim/pull/6784) 
* Fix missing translation keys for mime types  [#6766](https://github.com/decidim/decidim/pull/6766) 
* Add margin between back link and title  [#6854](https://github.com/decidim/decidim/pull/6854) 
* Align actions on Admin panel  [#6805](https://github.com/decidim/decidim/pull/6805) 
* Fix admin logs proposal presenter  [#6637](https://github.com/decidim/decidim/pull/6637) 
* Fix issues with move proposal fields to i18n  [#6838](https://github.com/decidim/decidim/pull/6838) 
* Fix proposals admin form when editing  [#7042](https://github.com/decidim/decidim/pull/7042) 
* Fix filter proposals by state in the admin  [#6883](https://github.com/decidim/decidim/pull/6883) 
* Don't show unpublished content in search engine  [#6863](https://github.com/decidim/decidim/pull/6863) 
* Fix the proposal body validation error messages  [#7156](https://github.com/decidim/decidim/pull/7156) 
* Fix form string length validation with carriage returns  [#7157](https://github.com/decidim/decidim/pull/7157) 
* Ignore the state_published_at field when importing proposals  [#7231](https://github.com/decidim/decidim/pull/7231) 
* Fix broken attachments with form validation errors  [#7336](https://github.com/decidim/decidim/pull/7336) 
* Fix removal of the address from proposals  [#7343](https://github.com/decidim/decidim/pull/7343) 
* Fix proposal title minimum length validation of 15 characters  [#7379](https://github.com/decidim/decidim/pull/7379) 

## 0.23 changelog

[decidim/CHANGELOG.md at release/0.23-stable · decidim/decidim · GitHub](https://github.com/decidim/decidim/blob/release/0.23-stable/CHANGELOG.md)

- Fix the proposal body validation error messages  [#7495](https://github.com/decidim/decidim/pull/7495) 
- Let admins delete proposal attachments  [#7435](https://github.com/decidim/decidim/pull/7435) 
- Fix proposals admin form when editing. Closes #7031 (#7042)  [#7051](https://github.com/decidim/decidim/pull/7051) 
- Backport "Fix comments newsletter participant ids" to v0.23  [#7184](https://github.com/decidim/decidim/pull/7184) 
- Fix issues with move proposal fields to i18n (#6838)  [#6842](https://github.com/decidim/decidim/pull/6842) 
- Add hashtags to comments  [#6429](https://github.com/decidim/decidim/pull/6429) 
- Debates filtering  [#6438](https://github.com/decidim/decidim/pull/6438) 
- Add scope to Budgets, Debates, Meetings, Proposals and Surveys components  [#6309](https://github.com/decidim/decidim/pull/6309) 
- Meetings by participants or groups  [#6095](https://github.com/decidim/decidim/pull/6095) 
- Add hashtags to debate  [#6396](https://github.com/decidim/decidim/pull/6396) 
- Keep filter and ordering params  [#6432](https://github.com/decidim/decidim/pull/6432) 
- Users can endorse debates.  [#6368](https://github.com/decidim/decidim/pull/6368) 
- Make character limit for comments configurable  [#6280](https://github.com/decidim/decidim/pull/6280) 
- Make proposals handle i18n  [#6285](https://github.com/decidim/decidim/pull/6285) 
- Add migration to update Proposal endorsement Notifications  [#6367](https://github.com/decidim/decidim/pull/6367) 
- Add tests to proposal_presenter  [#6265](https://github.com/decidim/decidim/pull/6265) 
- Import from proposals to answers  [#6163](https://github.com/decidim/decidim/pull/6163) 
- Add more than one attachment to proposals  [#6532](https://github.com/decidim/decidim/pull/6532) 
- Make maps actually configurable  [#6340](https://github.com/decidim/decidim/pull/6340) 
- Performance improvements for metrics  [#5575](https://github.com/decidim/decidim/pull/5575) 
- Make comments handle i18n  [#6276](https://github.com/decidim/decidim/pull/6276) 
- Fix proposals creation  [#6585](https://github.com/decidim/decidim/pull/6585) 
- Custom validator that checks string fields  [#6304](https://github.com/decidim/decidim/pull/6304) 
- Improve proposal selection  [#6213](https://github.com/decidim/decidim/pull/6213) 
- Fix admin logs proposal presenter (#6637)  [#6651](https://github.com/decidim/decidim/pull/6651) 
- Fix resource free text search  [#6465](https://github.com/decidim/decidim/pull/6465) 
- Fix proposal creation  [#6518](https://github.com/decidim/decidim/pull/6518) 
- Amendments validations enhancement for participatory texts  [#6344](https://github.com/decidim/decidim/pull/6344) 
- Bugfix 0.22.0.rc1  [#6381](https://github.com/decidim/decidim/pull/6381) 
- Fix rubocop errors arising from capybara upgrade  [#6197](https://github.com/decidim/decidim/pull/6197) 
- Fix bugs after proposals i18n move  [#6384](https://github.com/decidim/decidim/pull/6384) 
- Fix missing translation keys for mime types (#6766)  [#6795](https://github.com/decidim/decidim/pull/6795) 
- Remove legacy Proposals endorsements table  [#5643](https://github.com/decidim/decidim/pull/5643) 
- Revert "Custom validator that checks string fields (#6304)"  [#6316](https://github.com/decidim/decidim/pull/6316)
