### ISSUE TITLE
Integrate Assembly Proposals

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/decidim-module-liquidvoting#43]
This is analogous work to integrating Liquidvoting for Proposal Supports, but for Assembly Proposals.

- [x] ~add `decidim-assemblies` gem~ - Rather, we removed all except `decidim` gem
- [x] check for migrations or other assembly-specific dependencies
- [x] add routes to engine
- [x] add specs with proper assembly proposal fixtures

**Comment by davefrey** [comment]
We found just generalizing the route to have a variable placeholder instead of a hardcoded participatory process route, implements the change.

However, specs are harder, and we stopped after spending some time trying to get fixtures to support a spec proving the route does what we want (delegations on assembly proposals).

**Comment by davefrey** [comment]
We double the route declarations across the two participatory spaces (process and assembly), they're nearly identical, but this feels more comfortable than trying to understand if there's a magic parameter symbol for the space.

**Comment by oliverbarnes** [comment]
Agreed, it's better to be explicit here
