### ISSUE TITLE
Visually differentiate delegation button

### ISSUE THREAD

**Issue by jinjagit** [liquidvotingio/decidim-module-liquidvoting#47]
Use styling to visually differentiate our delegation button from the voting button on Decidim proposals.

Currently we have two red buttons for Support and Delegate, which disable appropriately, but otherwise this is confusing.
- [x] choose how to structurally and/or stylistically differentiate the support and delegation parts of this UI
- [x] insure all of our strings like "You delegated to:" are localizable in `en.yml`

**Comment by davefrey** [comment]
Rather than only styling, I propose reorganizing the components a bit to make things clearer. I've explained and given some screenshots to illustrate in [this discussion](https://github.com/liquidvotingio/decidim-module-liquidvoting/discussions/54).

Additionally in that same discussion I propose we offer more delegate information.

Let's experiment with discussing there, rather than here.

**Comment by davefrey** [comment]
Per [the discussion](https://github.com/liquidvotingio/decidim-module-liquidvoting/discussions/54) let's differentiate just by putting the Support button on top, and adding some text to introduce the Delegate select box and button.
